---
title: "Work Experience"
---

**Caesars Entertainment Inc. (Data Science Intern)**

During my time at Caesars Entertainment, I leveraged my expertise in SQL and Python to undertake sophisticated data cleaning initiatives. This entailed the innovative creation of new columns to augment the efficiency of data analysis and the application of specialized basketball logic to reclassify datasets, which significantly enhanced the accuracy and depth of data interpretation. My role also encompassed conducting thorough Exploratory Data Analysis and developing predictive models within the sports analytics domain, allowing for the discovery of pivotal variable relationships that informed strategic decision-making. In addition, I had the opportunity to collaborate closely with the director, assisting in providing expert consultations to other departments. Through these interactions, I contributed strategic insights that improved the forecasting modeling process, emphasizing my commitment to accuracy and the overall efficacy of analytical projects at Caesars Entertainment.

**Aria Group LLC. (A&R Data Analyst Intern) **

At Aria Group, my role was pivotal in enhancing internal data analysis processes for the company's programming. I was responsible for managing the infrastructure that facilitated statistical reporting and trend forecasting within the entertainment industry across various platforms. My efforts were focused on systematizing data charting and conducting detailed case studies, which played a crucial role in refining talent acquisition strategies. Additionally, I engaged in sourcing revenue data and employed my technical skills, particularly in R and Excel, to assess talent valuation in the marketplace comprehensively. This involved analyzing estimated revenues from diverse sources such as streaming platforms, concerts, merchandise, and financial statements, thereby providing a well-rounded perspective on talent and market dynamics. My contribution at Aria Group was instrumental in driving data-driven decisions and optimizing strategies for talent engagement and valuation.

**VTO Media & Entertainment (Marketing And Public Relations Intern)**

At VTO Media & Entertainment, my role was centered around forging strong connections with a broad range of clients and artists across social media platforms like TikTok and Instagram, as well as with representatives from various consumer brand companies, including Zara and Chu Choice. My responsibilities included identifying and nurturing emerging talents, such as Eden Choi, who notably became the South Korean representative for the International Federation of Magic Societies. My efforts contributed significantly to the company by facilitating the endorsement of artists with numerous sponsors, thereby enhancing their market presence and financial backing. Additionally, I was tasked with compiling weekly analyses on market trends and consumer behaviors, utilizing tools like Excel and PowerPoint. These analyses were instrumental in negotiating and securing sponsorship deals for artists with companies such as Sugarbear and Okaysou, leveraging detailed market insights to support the artists' growth and the firm's strategic objectives in the entertainment landscape.